include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude: [build/**, plugin/**]

linter:
  rules:
    camel_case_types: false
    unawaited_futures: false
    prefer_is_empty: false
    deprecated_member_use: false
