# ** ================== **
# **    PROJECT INFO    **
# ** ================== **
# -- Basic --
name: sonar_app
description: The dead simple way to connect with people and transfer files.
version: 0.4.0+0.1

# -- Flutter Settings --
environment:
  sdk: ">=2.8.0 <3.0.0"

# ** ================== **
# **    DEPENDENCIES    **
# ** ================== **
dependencies:
  # ** --- SDK -- **
  flutter:
    sdk: flutter

  # ** - User Defined - **
  # -- Management --
  flutter_bloc: ^6.1.0
  equatable: ^1.2.5

  # -- Device --
  flutter_compass: ^0.5.0
  geolocator: ^6.0.0+4
  permission_handler: ^5.0.1+1
  sensors: ^0.4.1+1
  soundpool: ^1.0.1
  vibration: ^1.2.4
  uuid: ^2.0.0

  # -- Extension --
  file: ^5.2.1
  graph_collection: ^1.1.2
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  image: ^2.1.18
  intl: ^0.15.8
  image_picker:
  logger: ^0.9.4
  path_provider: ^1.6.5
  path: ^1.7.0
  vector_math: any


  # -- Network --
  sonr_core:
    git:
      url: git@github.com:sonr-io/plugin.git
  chunked_stream: ^1.1.0
  flutter_webrtc: ^0.4.0
  http: ^0.12.0+4
  socket_io_client: ^0.9.11
  sqflite: ^1.3.0

  # -- UI/UX --
  animations: ^1.1.2
  flare_flutter: ^2.0.6
  floating_action_bubble: ^1.0.9
  flutter_gradients: ^1.0.0+2
  flutter_neumorphic: ^3.0.2
  fluttertoast: ^7.1.1
  page_transition: ^1.1.6
  path_drawing: ^0.4.1+1
  photo_view: ^0.10.2

# ** -- DEV Dependencies -- **
dev_dependencies:
  hive_generator: ^0.7.1
  build_runner: ^1.10.2

flutter_test:
  sdk: flutter
  
# ** ================== **
# **   FLUTTER BUILD    **
# ** ================== **
flutter:
  # -- Theme/Colors --
  uses-material-design: true

  # -- Media --
  assets:
    - assets/animations/
    - assets/audio/
    - assets/data/
    - assets/fonts/
    - assets/images/


  # -- Fonts --
  fonts:   
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/raleway/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/raleway/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/raleway/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/raleway/Raleway-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/raleway/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/raleway/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/raleway/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/raleway/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/raleway/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/raleway/Raleway-BlackItalic.ttf
          weight: 900
          style: italic