# ** ================== **
# **    PROJECT INFO    **
# ** ================== **
# -- Basic --
name: sonr_app
description: The dead simple way to connect with people and transfer files.
version: 0.9.1+20243
publish_to: none

# -- Flutter Settings --
environment:
  sdk: ">=2.8.0 <3.0.1"

# ** ================== **
# **    DEPENDENCIES    **
# ** ================== **
dependencies:
  # ** --- SDK -- **
  flutter:
    sdk: flutter

  # ** - User Defined - **
  # -- Management --
  file_picker: ^3.0.1
  file_picker_cross: ^4.3.2
  flutter_hooks: ^0.16.0
  get: ^4.1.3
  get_storage: ^2.0.2
  intl: ^0.17.0
  supercharged: ^2.0.0

  # -- Device --
  camerawesome: ^0.3.0-nullsafety
  flutter_compass: ^0.6.0
  flutter_keyboard_visibility: ^5.0.0
  flutter_systray: ^0.4.0
  geolocator: ^7.0.1
  location: ^4.1.1
  motion_sensors: ^0.1.0
  permission_handler: ^6.1.1
  platform_device_id: ^1.0.1
  url_launcher: ^6.0.2
  warble: ^0.0.2

  # -- Data --
  audioplayers: ^0.18.3
  open_file: ^3.1.0
  photo_manager: ^1.1.4
  path: ^1.7.0
  path_provider: ^2.0.1
  vector_math: ^2.1.0
  video_player: ^2.1.1

  # -- Network --
  mime: ^1.0.0
  moor: ^4.2.1
  sqlite3_flutter_libs: ^0.4.1
  receive_sharing_intent: ^1.4.3

  # -- Plugins --
  sonr_plugin:
    path: ../plugin/

  # -- UI/UX --
  animated_widgets: ^1.0.6
  carousel_slider: ^3.0.0
  fl_chart: ^0.35.0
  flutter_gradients: ^1.0.0+3
  keyboard_actions: ^3.4.0
  lottie: ^1.0.1
  material_floating_search_bar: ^0.3.4
  photo_view: ^0.11.1
  rive: ^0.7.1

# ** -- DEV Dependencies -- **
dev_dependencies:
  build_runner:
  moor_generator:

flutter_test:
  sdk: flutter

# ** ================== **
# **   FLUTTER BUILD    **
# ** ================== **
flutter:
  # -- Theme/Colors --
  uses-material-design: true

  fonts:
  - family:  Manrope
    fonts:
      - asset: assets/fonts/Manrope-200.ttf
        weight: 200
      - asset: assets/fonts/Manrope-300.ttf
        weight: 300
      - asset: assets/fonts/Manrope-400.ttf
        weight: 400
      - asset: assets/fonts/Manrope-500.ttf
        weight: 500
      - asset: assets/fonts/Manrope-600.ttf
        weight: 600
      - asset: assets/fonts/Manrope-700.ttf
        weight: 700
      - asset: assets/fonts/Manrope-800.ttf
        weight: 800

  - family:  OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf

  - family:  SonrIcons
    fonts:
      - asset: assets/fonts/Sonricons.ttf

  # -- Media --
  assets:
    - assets/cards/
    - assets/fonts/
    - assets/images/
    - assets/rive/
    - assets/sounds/



