# ** ================== **
# **    PROJECT INFO    **
# ** ================== **
# -- Basic --
name: sonar_app
description: The dead simple way to connect with people and transfer files.
version: 1.0.0+1

# -- Flutter Settings --
environment:
  sdk: ">=2.2.2 <3.0.0"

# ** ================== **
# **    DEPENDENCIES    **
# ** ================== **
dependencies:
  # ** --- SDK -- **
  flutter:
    sdk: flutter

  # ** - User Defined - **
  # -- BLoC --
  flutter_bloc: ^6.0.0
  equatable: ^1.2.0

  # -- Device --
  flutter_sensor_compass: ^0.1.1
  geolocator: ^5.3.1
  permission_handler: ^5.0.0+hotfix.3
  sensors: ^0.4.1+1
  soundpool: ^1.0.1
  vibration: ^1.2.4
  uuid: 2.0.0

  # -- Extension --
  characters: ^1.0.0
  enum_to_string: ^1.0.9
  intl: ^0.15.8
  image_picker:
  path_provider: ^1.6.5
  path: ^1.7.0
  sortedmap: ^0.4.2+1

  # -- Network --
  chunked_stream: ^1.1.0
  flutter_webrtc: ^0.2.6
  socket_io_client: ^0.9.1
  http: ^0.12.0+4

  # -- UI/UX --
  logger: ^0.8.3
  rflutter_alert: ^1.0.2
  flutter_neumorphic: ^3.0.2

# ** -- TEST -- **
dev_dependencies:
  flutter_test:
    sdk: flutter

# ** ================== **
# **   FLUTTER BUILD    **
# ** ================== **
flutter:
  # -- Theme/Colors --
  uses-material-design: true

  # -- Media --
  assets:
    - assets/animations/
    - assets/images/
    - assets/images/social/
    - assets/images/headers/
    - assets/audio/

  # -- Fonts --
  fonts:
    - family: Boxicons
      fonts:
        - asset: assets/fonts/boxicons.ttf
          weight: 400
