# ** ================== **
# **    PROJECT INFO    **
# ** ================== **
# -- Basic --
name: sonar_app
description: The dead simple way to connect with people and transfer files.
version: 0.4.0+0.1

# -- Flutter Settings --
environment:
  sdk: ">=2.8.0 <3.0.0"

# ** ================== **
# **    DEPENDENCIES    **
# ** ================== **
dependencies:
  # ** --- SDK -- **
  flutter:
    sdk: flutter

  # ** - User Defined - **
  # -- Management --
  flutter_hooks: ^0.15.0
  get: ^3.23.1
  intl: ^0.15.8
  logger: ^0.9.4

  # -- Device --
  flutter_compass: ^0.5.0
  geolocator: ^6.0.0+4
  permission_handler: ^5.0.1+1
  sensors: ^0.4.1+1
  vibration: ^1.2.4

  # -- Data --
  gallery_saver: ^2.0.1
  path: ^1.7.0
  path_provider: ^1.6.7
  shared_preferences: ^0.5.12+4

  # -- Network --
  sqflite: ^1.3.0
  sonr_core:
    git:
      url: git@github.com:sonr-io/plugin.git
      ref: release

  # -- UI/UX --
  clippy_flutter: ^1.1.0
  floating_action_bubble: ^1.0.9
  flutter_boxicons: ^2.0.1
  flutter_gradients: ^1.0.0+2
  flutter_neumorphic: ^3.0.2
  flutter_staggered_grid_view: ^0.3.2
  google_fonts: ^1.1.1
  rive: ^0.6.2
  simple_animations: ^2.4.0

# ** -- DEV Dependencies -- **
dev_dependencies:
  build_runner: ^1.10.2

flutter_test:
  sdk: flutter

# ** ================== **
# **   FLUTTER BUILD    **
# ** ================== **
flutter:
  # -- Theme/Colors --
  uses-material-design: true

  # -- Media --
  assets:
    - assets/animations/
    - assets/images/
