# ** ================== **
# **    PROJECT INFO    **
# ** ================== **
# -- Basic --
name: sonr_app
description: The dead simple way to connect with people and transfer files.
version: 0.9.1+149
publish_to: none

# -- Flutter Settings --
environment:
  sdk: ">=2.8.0 <3.0.1"

# ** ================== **
# **    DEPENDENCIES    **
# ** ================== **
dependencies:
  # ** --- SDK -- **
  flutter:
    sdk: flutter

  # ** - User Defined - **
  # -- Management --
  flutter_hooks: ^0.16.0
  get: ^4.1.3
  get_storage: ^2.0.2
  intl: ^0.17.0
  supercharged: ^2.0.0

  # -- Device --
  camerawesome: ^0.3.0-nullsafety
  flutter_compass: ^0.6.0
  flutter_keyboard_visibility: ^5.0.0
  geolocator: ^7.0.1
  motion_sensors: ^0.1.0
  permission_handler: ^6.1.1
  url_launcher: ^6.0.2

  # -- Data --
  better_player: ^0.0.55
  open_file:
  photo_manager: ^1.0.6
  path: ^1.7.0
  path_provider: ^2.0.1
  vector_math: ^2.1.0

  # -- Network --
  moor: ^4.2.1
  sqlite3_flutter_libs: ^0.4.1
  receive_sharing_intent: ^1.4.3

  # -- Plugins --
  sonr_core:
    path: plugins/sonr

  # -- UI/UX --
  animated_widgets: ^1.0.6
  flutter_custom_clippers: ^1.1.2
  flutter_gradients: ^1.0.0+3
  flutter_neumorphic: ^3.0.4+1
  lottie: ^1.0.1
  photo_view: ^0.11.1
  rive: ^0.7.1

# ** -- DEV Dependencies -- **
dev_dependencies:
  build_runner:
  moor_generator:

flutter_test:
  sdk: flutter

# ** ================== **
# **   FLUTTER BUILD    **
# ** ================== **
flutter:
  # -- Theme/Colors --
  uses-material-design: true

  fonts:
  - family:  SonrIcons
    fonts:
      - asset: assets/fonts/sonr_icons.ttf

  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-300.ttf
        weight: 300
      - asset: assets/fonts/Poppins-300-Italic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Poppins-400.ttf
        weight: 400
      - asset: assets/fonts/Poppins-400-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Poppins-500.ttf
        weight: 500
      - asset: assets/fonts/Poppins-500-Italic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-600.ttf
        weight: 600
      - asset: assets/fonts/Poppins-600-Italic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Poppins-700.ttf
        weight: 700
      - asset: assets/fonts/Poppins-700-Italic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Poppins-800.ttf
        weight: 800
      - asset: assets/fonts/Poppins-800-Italic.ttf
        weight: 800
        style: italic

  # -- Media --
  assets:
    - assets/rive/
    - assets/lottie/
    - assets/fonts/
    - assets/images/


