# ** ================== **
# **    PROJECT INFO    **
# ** ================== **
# -- Basic --
name: sonr_app
description: The dead simple way to connect with people and transfer files.
version: 0.9.1+24
publish_to: none

# -- Flutter Settings --
environment:
  sdk: ">=2.8.0 <3.0.1"

# ** ================== **
# **    DEPENDENCIES    **
# ** ================== **
dependencies:
  # ** --- SDK -- **
  flutter:
    sdk: flutter

  # ** - User Defined - **
  # -- Management --
  flutter_hooks: ^0.16.0
  get: ^3.25.4
  get_storage: ^1.4.0
  intl: ^0.17.0
  supercharged: ^2.0.0

  # -- Device --
  camerawesome: ^0.3.0-nullsafety
  flutter_compass: ^0.6.0
  geocode: ^0.1.3
  geolocator: ^6.2.1
  motion_sensors: ^0.1.0
  permission_handler: ^5.1.0+2
  url_launcher: ^6.0.2

  # -- Data --
  better_player: ^0.0.55
  open_file: ^3.0.3
  photo_manager: ^1.0.6
  path: ^1.7.0
  path_provider: ^1.6.27
  vector_math: ^2.1.0

  # -- Network --
  receive_sharing_intent: ^1.4.3
  sqflite: ^2.0.0+1
  sonr_core:
    path: ../plugin/

  # -- UI/UX --
  animated_widgets: ^1.0.6
  flutter_custom_clippers: ^1.1.2
  flutter_gradients: ^1.0.0+3
  flutter_neumorphic: ^3.0.4+1
  google_fonts: ^1.1.2
  lottie: ^1.0.1
  photo_view: ^0.10.3
  rive: ^0.6.8

# ** -- DEV Dependencies -- **
dev_dependencies:
  build_runner: ^1.10.2

flutter_test:
  sdk: flutter

# ** ================== **
# **   FLUTTER BUILD    **
# ** ================== **
flutter:
  # -- Theme/Colors --
  uses-material-design: true

  fonts:
  - family:  SonrIcons
    fonts:
      - asset: assets/fonts/sonr_icons.ttf

  # -- Media --
  assets:
    - assets/animations/rive/
    - assets/animations/lottie/
    - assets/fonts/
    - assets/illustrations/


