# ** ================== **
# **    PROJECT INFO    **
# ** ================== **
# -- Basic --
name: sonar_app
description: The dead simple way to connect with people and transfer files.
version: 1.0.0+1

# -- Flutter Settings --
environment:
  sdk: ">=2.2.2 <3.0.0"

# ** ================== **
# **    DEPENDENCIES    **
# ** ================== **
dependencies:
  # ** --- SDK -- **
  flutter:
    sdk: flutter

  # ** - User Defined - **
  # -- BLoC --
  flutter_bloc: ^6.0.0
  equatable: ^1.2.0

  # -- Device --
  flutter_sensor_compass: ^0.1.1
  geolocator: ^5.3.1
  permission_handler: ^5.0.0+hotfix.3
  sensors: ^0.4.1+1
  soundpool: ^1.0.1
  vibration: ^1.2.4
  uuid: 2.0.0

  # -- Extension --
  characters: ^1.0.0
  graph_collection: ^1.1.2
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  intl: ^0.15.8
  image_picker:
    logger: ^0.8.3
  path_provider: ^1.6.5
  path: ^1.7.0
  tuple: ^1.0.3

  # -- Network --
  chunked_stream: ^1.1.0
  flutter_webrtc: ^0.2.6
  socket_io_client: ^0.9.1
  http: ^0.12.0+4

  # -- UI/UX --
  animations: ^1.1.2
  boxicons_flutter: ^1.1.0
  flutter_gradients: ^1.0.0+2
  flutter_neumorphic: ^3.0.2
  page_transition: ^1.1.6

# ** -- TEST -- **
dev_dependencies:
  hive_generator: ^0.7.1
  build_runner: ^1.10.2
  
  flutter_test:
    sdk: flutter

# ** ================== **
# **   FLUTTER BUILD    **
# ** ================== **
flutter:
  # -- Theme/Colors --
  uses-material-design: true

  # -- Media --
  assets:
    - assets/animations/
    - assets/images/
    - assets/images/social/
    - assets/images/headers/
    - assets/audio/

  # -- Fonts --
  fonts:   
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/raleway/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/raleway/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/raleway/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/raleway/Raleway-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/raleway/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/raleway/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/raleway/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/raleway/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/raleway/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/raleway/Raleway-BlackItalic.ttf
          weight: 900
          style: italic