# ** ================== **
# **    PROJECT INFO    **
# ** ================== **
# -- Basic --
name: sonr_app
description: The dead simple way to connect with people and transfer files.
version: 0.10.0
publish_to: none

# -- Flutter Settings --
environment:
  sdk: ">=2.13.0 <3.0.0"

environment_config:
  path: env.dart # optional, result file path against `lib/` folder
  fields: # set of fields for command
    map_key:
      env_var: map_key
    map_secret:
      env_var: map_secret
    ip_key:
      env_var: ip_key
    rapid_key:
      env_var: rapid_key
    hs_key:
      env_var: hs_key
    hs_secret:
      env_var: hs_secret
    hub_key:
      env_var: hub_key
    hub_secret:
      env_var: hub_secret
    icom_appID:
      env_var: icom_appID
    icom_iosKey:
      env_var: icom_iosKey
    icom_androidKey:
      env_var: icom_androidKey
    thread_db:
      env_var: thread_db

# ** ================== **
# **    DEPENDENCIES    **
# ** ================== **
dependencies:
  # ** --- SDK -- **
  flutter:
    sdk: flutter

  # ** - User Defined - **
  # -- Management --
  bip39: ^1.0.6
  cloud_firestore: ^2.4.0
  environment_config: ^3.0.0
  firebase_analytics: ^8.1.1
  firebase_core: ^1.2.1
  firebase_crashlytics: ^2.0.6
  firebase_messaging: ^10.0.3
  get: ^4.2.4
  get_storage: ^2.0.2
  intercom_flutter: ^5.0.0
  intl: ^0.17.0
  logger: ^1.0.0

  # -- Device --
  camerawesome: ^0.3.0+1
  connectivity: ^3.0.6
  geolocator: ^7.0.3
  package_info: ^2.0.2
  permission_handler: ^8.0.1
  url_launcher: ^6.0.3

  # -- Data --
  file_picker: ^3.0.2+2
  flutter_contacts: ^1.1.0+3
  open_file: ^3.2.0
  photo_manager: ^1.2.0
  path: ^1.8.0
  path_provider: ^2.0.1
  share_plus: ^2.1.4
  vector_math: ^2.1.0
  video_player: ^2.1.6

  # -- Network --
  mime: ^1.0.0
  moor: ^4.2.2
  namebase: ^0.1.1
  receive_sharing_intent: ^1.4.5
  sqlite3_flutter_libs: ^0.5.0
  uni_links: ^0.5.1

  # -- Plugins --
  sonr_plugin:
    path: ../plugin

  # -- UI/UX --
  animate_do: ^2.0.0
  flutter_svg: ^0.22.0
  introduction_screen: ^2.1.0
  lottie: ^1.0.1
  pin_code_fields: ^7.3.0
  rive: ^0.7.7
  showcaseview: ^1.0.0
  supercharged: ^2.0.0

# ** -- DEV Dependencies -- **
dev_dependencies:
  build_runner: ^2.0.5
  moor_generator: ^4.4.0

flutter_test:
  sdk: flutter

# ** ================== **
# **   FLUTTER BUILD    **
# ** ================== **
flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-100.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-100-italic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat-300.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-300-italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-400.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-400-italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-500.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-500-italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-700-italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-700.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-700-italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-900.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-900-italic.ttf
          weight: 900
          style: italic

    - family: SonrIcons
      fonts:
        - asset: assets/fonts/Sonricons.ttf

    - family: SonrNavIcons
      fonts:
        - asset: assets/fonts/SonrNavIcons.ttf

  # -- Media --
  assets:
    - assets/animations/lottie/
    - assets/animations/rive/
    - assets/data/
    - assets/fonts/
    - assets/icons/Chart/
    - assets/icons/Communication/
    - assets/icons/DateTime/
    - assets/icons/Design/
    - assets/icons/Device/
    - assets/icons/FileSystem/
    - assets/icons/Finance/
    - assets/icons/Food/
    - assets/icons/Formatting/
    - assets/icons/MediaControl/
    - assets/icons/Medical/
    - assets/icons/Navigation/
    - assets/icons/SelfCare/
    - assets/icons/Shopping/
    - assets/icons/SocialMedia/
    - assets/icons/Sports/
    - assets/icons/UI/
    - assets/images/illustrations/
    - assets/images/svg/
    - assets/images/utility/
    - assets/sounds/
