# ** ================== **
# **    PROJECT INFO    **
# ** ================== **
# -- Basic --
name: sonar_app
description: The dead simple way to connect with people and transfer files.
version: 1.0.0+1

# -- Flutter Settings --
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

# ** ================== **
# **    DEPENDENCIES    **
# ** ================== **
dependencies:
  # ** --- SDK -- **
  flutter:
    sdk: flutter

  # ** - User Defined - **
  # -- BLoC --
  flutter_bloc: ^3.2.0
  equatable: ^1.1.0

  # -- Device --
  flutter_compass:
  geolocator: ^3.0.0
  permission_handler:
  sensors: ^0.4.1+1
  socket_io: ^0.9.3
  uuid: 2.0.0

  # -- Extension --
  intl: ^0.15.8
  path_provider: ^0.5.0+1

  # -- Network --
  web_socket_channel: "^1.0.8"

  # -- UI/UX --
  flutter_spinkit: "^3.1.0"
  rflutter_alert: ^1.0.2

# ** -- TEST -- **
dev_dependencies:
  flutter_test:
    sdk: flutter


# ** ================== **
# **   FLUTTER BUILD    **
# ** ================== **
flutter:
# -- Theme/Colors --
  uses-material-design: true

# -- Media --
  assets:
    - assets/animations/
    - assets/images/
    - assets/images/social/
    - assets/images/headers/

# -- Fonts --
  fonts:
    - family: Boxicons
      fonts:
        - asset: assets/fonts/boxicons.ttf
          weight: 400
