# ** ================== **
# **    PROJECT INFO    **
# ** ================== **
# -- Basic --
name: sonr_app
description: The dead simple way to connect with people and transfer files.
version: 0.9.3+2
publish_to: none

# -- Flutter Settings --
environment:
  sdk: '>=2.12.0 <3.0.0'

environment_config:
  path: env.dart # optional, result file path against `lib/` folder
  fields: # set of fields for command
    ip_key:
      env_var: ip_key
    rapid_host:
      env_var: rapid_host
    rapid_key:
      env_var: rapid_key
    hs_key:
      env_var: hs_key
    hs_secret:
      env_var: hs_secret
    hub_key:
      env_var: hub_key
    hub_secret:
      env_var: hub_secret
    sentry_dsn:
      env_var: sentry_dsn
    storj_key:
      env_var: storj_key
    storj_root_password:
      env_var: storj_root_password

# ** ================== **
# **    DEPENDENCIES    **
# ** ================== **
dependencies:
  # ** --- SDK -- **
  flutter:
    sdk: flutter

  # ** - User Defined - **
  # -- Management --
  bip39: ^1.0.6
  crypton: ^2.0.1
  environment_config: ^3.0.0
  file_picker: ^3.0.1
  flutter_hooks: ^0.17.0
  flutter_secure_storage: ^4.2.0
  get: ^4.1.4
  get_storage: ^2.0.2
  intl: ^0.17.0
  logger: ^1.0.0
  sentry_flutter: ^5.0.0

  # -- Device --
  camerawesome: ^0.3.0-nullsafety
  connectivity: ^3.0.6
  flutter_blue: ^0.8.0
  flutter_compass: ^0.6.0
  flutter_keyboard_visibility: ^5.0.1
  geolocator: ^7.0.3
  motion_sensors: ^0.1.0
  permission_handler: ^8.0.1
  platform_device_id: ^1.0.1
  url_launcher: ^6.0.3

  # -- Data --
  audioplayers: ^0.19.0
  open_file: ^3.2.0
  photo_manager: ^1.2.0
  path: ^1.8.0
  path_provider: ^2.0.1
  share: ^2.0.1
  vector_math: ^2.1.0
  video_player: ^2.0.0-nullsafety.9

  # -- Network --
  feedback: ^1.2.2
  flutter_email_sender: ^5.0.0
  mime: ^1.0.0
  moor: ^4.3.2
  receive_sharing_intent: ^1.4.5
  uni_links: ^0.5.1

  # -- Plugins --
  posthog_flutter:
    git: git@github.com:sonr-io/posthog-flutter.git
  sonr_plugin:
    git: git@github.com:sonr-io/plugin.git
    #path: ../plugin/ #-- Uncomment for Local Development

  # -- UI/UX --
  animate_do: ^2.0.0
  lottie: ^1.0.1
  rive: ^0.7.7
  supercharged: ^2.0.0

# ** -- DEV Dependencies -- **
dev_dependencies:
  build_runner: ^2.0.2
  moor_generator: ^4.2.2

flutter_test:
  sdk: flutter

# ** ================== **
# **   FLUTTER BUILD    **
# ** ================== **
flutter:
  # -- Theme/Colors --
  uses-material-design: true

  fonts:
  - family: AlongSans
    fonts:
    - asset: assets/fonts/AlongSans.otf

  - family:  RFlex
    fonts:
      - asset: assets/fonts/RFlex-100.otf
        weight: 100
      - asset: assets/fonts/RFlex-100-italic.otf
        weight: 100
        style: italic
      - asset: assets/fonts/RFlex-300.otf
        weight: 300
      - asset: assets/fonts/RFlex-300-italic.otf
        weight: 300
        style: italic
      - asset: assets/fonts/RFlex-400.otf
        weight: 400
      - asset: assets/fonts/RFlex-400-italic.otf
        weight: 400
        style: italic
      - asset: assets/fonts/RFlex-500.otf
        weight: 500
      - asset: assets/fonts/RFlex-500-italic.otf
        weight: 500
        style: italic
      - asset: assets/fonts/RFlex-700-italic.otf
        weight: 700
        style: italic
      - asset: assets/fonts/RFlex-700.otf
        weight: 700
      - asset: assets/fonts/RFlex-700-italic.otf
        weight: 700
        style: italic
      - asset: assets/fonts/RFlex-900.otf
        weight: 900
      - asset: assets/fonts/RFlex-900-italic.otf
        weight: 900
        style: italic

  - family:  SonrIcons
    fonts:
      - asset: assets/fonts/Sonricons.ttf

  - family:  SonrNavIcons
    fonts:
      - asset: assets/fonts/SonrNavIcons.ttf

  # -- Media --
  assets:
    - assets/cards/
    - assets/fonts/
    - assets/images/
    - assets/illustrations/
    - assets/animations/
    - assets/sounds/



