# ** ================== **
# **    PROJECT INFO    **
# ** ================== **
# -- Basic --
name: sonar_app
description: The dead simple way to connect with people and transfer files.
version: 0.8.0+0.0.1

# -- Flutter Settings --
environment:
  sdk: ">=2.8.0 <3.0.0"

# ** ================== **
# **    DEPENDENCIES    **
# ** ================== **
dependencies:
  # ** --- SDK -- **
  flutter:
    sdk: flutter

  # ** - User Defined - **
  # -- Management --
  flutter_hooks: ^0.15.0
  get: ^3.23.1
  intl: ^0.15.8
  logger: ^0.9.4
  url_launcher: ^5.7.10

  # -- Device --
  flutter_compass: ^0.5.1
  geolocator: ^6.0.0+4
  permission_handler: ^5.0.1+1
  sensors: ^0.4.1+1

  # -- Data --
  image_gallery_saver: ^1.6.7
  image_picker: ^0.6.7+17
  media_gallery: ^0.1.5
  path: ^1.7.0
  path_provider: ^1.6.7
  shared_preferences: ^0.5.12+4
  video_player: ^1.0.1

  # -- Network --
  receive_sharing_intent: ^1.4.2
  sqflite: ^1.3.0
  sonr_core:
    path: ../plugin/
    # git:
    #   url: git@github.com:sonr-io/plugin.git

  # -- UI/UX --
  flutter_custom_clippers: ^1.1.2
  flutter_dropdown: ^0.0.8
  flutter_gradients: ^1.0.0+2
  flutter_neumorphic: ^3.0.2
  flutter_staggered_grid_view: ^0.3.2
  google_fonts: ^1.1.1
  rive: ^0.6.2
  simple_animations: ^2.4.0

# ** -- DEV Dependencies -- **
dev_dependencies:
  build_runner: ^1.10.2

flutter_test:
  sdk: flutter

# ** ================== **
# **   FLUTTER BUILD    **
# ** ================== **
flutter:
  # -- Theme/Colors --
  uses-material-design: true

  fonts:
  - family:  SonrIcons
    fonts:
      - asset: assets/fonts/sonr_icons.ttf

  # -- Media --
  assets:
    - assets/animations/
    - assets/fonts/
    - assets/images/
    - assets/keys.json


