# ** ================== **
# **    PROJECT INFO    **
# ** ================== **
# -- Basic --
name: sonr_app
description: The dead simple way to connect with people and transfer files.
version: 0.9.1+240
publish_to: none

# -- Flutter Settings --
environment:
  sdk: ">=2.8.0 <3.0.1"

# ** ================== **
# **    DEPENDENCIES    **
# ** ================== **
dependencies:
  # ** --- SDK -- **
  flutter:
    sdk: flutter

  # ** - User Defined - **
  # -- Management --
  file_picker: ^3.0.1
  flutter_hooks: ^0.16.0
  get: ^4.1.3
  get_storage: ^2.0.2
  intl: ^0.17.0
  supercharged: ^2.0.0

  # -- Device --
  camerawesome: ^0.3.0-nullsafety
  flutter_compass: ^0.6.0
  flutter_keyboard_visibility: ^5.0.0
  geolocator: ^7.0.1
  motion_sensors: ^0.1.0
  permission_handler: ^6.1.1
  url_launcher: ^6.0.2

  # -- Data --
  audioplayers: ^0.18.3
  better_player: ^0.0.55
  open_file: ^3.1.0
  photo_manager: ^1.1.1
  path: ^1.7.0
  path_provider: ^2.0.1
  vector_math: ^2.1.0

  # -- Network --
  moor: ^4.2.1
  sqlite3_flutter_libs: ^0.4.1
  receive_sharing_intent: ^1.4.3

  # -- Plugins --
  sonr_core:
    path: plugins/sonr

  # -- UI/UX --
  animated_widgets: ^1.0.6
  flutter_gradients: ^1.0.0+3
  flutter_neumorphic: ^3.0.4+1
  lottie: ^1.0.1
  photo_view: ^0.11.1
  rive: ^0.7.1
  mime: ^1.0.0

# ** -- DEV Dependencies -- **
dev_dependencies:
  build_runner:
  moor_generator:

flutter_test:
  sdk: flutter

# ** ================== **
# **   FLUTTER BUILD    **
# ** ================== **
flutter:
  # -- Theme/Colors --
  uses-material-design: true

  fonts:
  - family:  Manrope
    fonts:
      - asset: assets/fonts/Manrope-VariableFont_wght.ttf

  - family:  OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf

  - family:  SonrIcons
    fonts:
      - asset: assets/fonts/sonr_icons.ttf

  # -- Media --
  assets:
    - assets/bar/
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - assets/rive/
    - assets/sounds/
    - assets/share/



