package main

// DO NOT EDIT, this file is generated by hover at compile-time for the sonr_plugin plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	sonr_plugin "github.com/sonr-io/plugin/go"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&sonr_plugin.SonrCorePlugin{}))
}
