package main

// DO NOT EDIT, this file is generated by hover at compile-time for the vibrato plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	warble "github.com/jslater89/warble/go"
	// path_provider "github.com/go-flutter-desktop/plugins/path_provider"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(warble.New()))
}
