default_platform(:ios)

platform :ios do
  desc "iOS Assemble"
  lane :assemble do
    if is_ci
      create_keychain(
        name: "fastlane-keychain",
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false,
        require_create: true,
      )
      match(
        type: "appstore",
        readonly: is_ci,
        keychain_name: "fastlane-keychain"
      )
    end
    # increment_build_number(
    #   build_number: flutter_version()["version_code"],
    # )
    # increment_version_number(
    #   version_number: flutter_version()["version_name"]
    # )
  end

  desc "iOS Build"
  lane :build do
    Dir.chdir "../.." do
      sh("flutter", "build", "ios", "--release", "--no-codesign")
    end
    build_app(scheme: "Runner",
      workspace: "Runner.xcworkspace",
      export_method: "app-store",
      export_options: {
      provisioningProfiles: {
          "io.sonr.apple" => "match AppStore io.sonr.apple",
          "io.sonr.apple.sharing" => "match AppStore io.sonr.apple.sharing"
        },
      })
  end

  desc "Deploy to (Internal) - App Store"
  lane :deploy_internal do
    upload_to_testflight(skip_waiting_for_build_processing: !is_ci, expire_previous_builds: true)
  end
end
