# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")
    build_app(scheme: "Runner",
            workspace: "Runner.xcworkspace",
            export_options: {
              method: "app-store",
              provisioningProfiles: {
                "io.sonr.apple" => "match AppStore io.sonr.apple",
                "io.sonr.apple.sharing" => "match AppStore io.sonr.apple.sharing"
              },
            })
    upload_to_testflight(skip_waiting_for_build_processing: false, expire_previous_builds: true)
  end
end
