# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Upload Binary to closed alpha"
  lane :alpha do
    upload_to_play_store(aab: "../build/app/outputs/bundle/release/app-release.aab",track: 'alpha')
  end

  desc "Upload Binary to open beta"
  lane :beta do
    upload_to_play_store(aab: "../build/app/outputs/bundle/release/app-release.aab",track: 'beta')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
