# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new build to Internal Track on Play"
  lane :internal do
    increment_version_code(
      gradle_file_path: 'app/build.gradle'
    )
    supply(aab: "../build/app/outputs/bundle/release/app-release.aab", track: 'internal')
  end
end
