# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new internal build to play store"
  lane :internal do
    supply(aab: "../build/app/outputs/bundle/release/app-release.aab", track: 'internal',  track_promote_to: 'internal')
  end

  desc "Deploy a new version to the Google Play"
  lane :beta do
    supply(aab: "../build/app/outputs/bundle/release/app-release.aab", track: 'beta',  track_promote_to: 'beta')
  end
end
