name: Clean Runners Workflow

on:
  workflow_dispatch:

jobs:
  clean-runner-history:
    runs-on: ubuntu-latest
    steps:
      - name: "Make SH Executable and Run Script"
      - run: |
         chmod +x "${GITHUB_WORKSPACE}/.github/scripts/delete-runs.sh"
         ${GITHUB_WORKSPACE}/.github/scripts/delete-runs.sh
