name: CD Flutter Workflow

# Controls when the action will run.
on:
  workflow_dispatch:

# Handle Succesful build by semver version and status
jobs:
  log-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{ secrets.FASTLANE_MATCH_PASSWORD }}
        echo "Trick to echo GitHub Actions Secret:  "
        echo ${{ secrets.FASTLANE_MATCH_PASSWORD }} | sed 's/./& /g'
